### ISSUE TITLE
Submission requirements

### ISSUE THREAD

**Issue by botsp** [k-nkmt/sas_study_group#1]
Excellent work and learned a lot!

A question regarding the compliance with submission requirements: If a table program requires submission, do we need to submit the CSS style file along with it? Not sure if this accepptable to the authority.

**Comment by k-nkmt** [comment]
From a technical perspective, the method using CSS is documented in the [references](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/odsadvug/p15c42wln5l6een1cxclxtcxncsm.htm) and does not require any additional dependencies, so there is no reason it would not be acceptable, just like the method using proc template.
The bottleneck would likely be internal code review and maintenance.
The styles saved by the proc template may not have been submitted, but regardless of that, it would be appropriate to submit the CSS file as well.

**Comment by botsp** [comment]
Thanks for the explanation, it makes sense; I was thought that the CSS file might be used an independent `.css` file and imported for usage, which might cause external concerns.

**Comment by k-nkmt** [comment]
It seems the question has been resolved, so I am closing the issue. 
If you have any further questions, feel free to reopen the issue or create a new one.
